# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 암기특화 (타이머 플래시카드)
email: studynewbook@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  영단어 암기에 효과적인 플래시카드 방식에 
  가변 망각방지 타이머가 자동으로 다음노출시간을 계산해주므로 
  단어학습 효율이 극대화 됩니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://studynewbook.github.io"
twitter_username: 
github_username: studynewbook

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

encoding: utf-8
# highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
